trigger:
- master
jobs:
- job: 'Perl Module'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Perl58:
        perl.version: '5.8'
      Perl510:
        perl.version: '5.10'
      perl512:
        perl.version: '5.12'
      perl514:
        perl.version: '5.14'
      Perl516:
        perl.version: '5.16'
      perl518:
        perl.version: '5.18'
      perl520:
        perl.version: '5.20'
      perl522:
        perl.version: '5.22'
      perl524:
        perl.version: '5.24'
      Perl526:
        perl.version: '5.26'
      perl528:
        perl.version: '5.28'
      perl530:
        perl.version: '5.30'
    maxParallel: 4

  steps:
  - task: UsePerlVersion@0
    inputs:
      versionSpec: '$(perl.version)'
      architecture: 'x64'
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
